window.LQEnvironmentBases={
  version:101,
  slots:[
    {id:"sky",z:1,parallax:.02},
    {id:"celestial",z:2,parallax:.04},
    {id:"farMountains",z:3,parallax:.08},
    {id:"midMountains",z:4,parallax:.12},
    {id:"valley",z:5,parallax:.16},
    {id:"water",z:6,parallax:.18},
    {id:"heroMountain",z:7,parallax:.22},
    {id:"structures",z:8,parallax:.24},
    {id:"mist",z:10,parallax:.28},
    {id:"foreground",z:11,parallax:.34},
    {id:"flora",z:12,parallax:.38},
    {id:"particles",z:13,parallax:.45},
    {id:"weather",z:14,parallax:.48},
    {id:"lighting",z:15,parallax:0}
  ],
  defaultScene:"premium-alpine",
  scenes:{
    "premium-alpine":{
      id:"premium-alpine",
      label:"Premium Alpine",
      layers:{
        sky:"assets/journey/premium-v101/sky.png?v=101",
        farMountains:"assets/journey/premium-v101/far-mountains.png?v=101",
        water:"assets/journey/premium-v101/waterfall-valley.png?v=101",
        heroMountain:"assets/journey/premium-v101/hero-mountain.png?v=101",
        foreground:"assets/journey/premium-v101/foreground.png?v=101"
      },
      effects:{particles:"none",weather:"clear",lighting:"golden",mist:true},
      characterAnchors:{
        home:{
          x:parseFloat(window.LQJourneyConfig?.layout?.companion?.left)||20,
          y:parseFloat(window.LQJourneyConfig?.layout?.companion?.top)||74
        },
        trailStart:{x:39,y:64},
        trailMid:{x:57,y:47},
        summit:{x:76,y:24}
      }
    }
  },
  transition:{
    durationMs:650,
    easing:"cubic-bezier(.22,.8,.24,1)",
    mode:"crossfade"
  }
};
