window.LQEnvironmentBases={
  version:1,
  layerOrder:["sky","celestial","farMountains","midMountains","valley","water","heroMountain","structures","trail","mist","foreground","flora","particles","weather","lighting"],
  sceneSlots:{
    sky:{parallax:.02,editable:true},
    celestial:{parallax:.04,editable:true},
    farMountains:{parallax:.08,editable:true},
    midMountains:{parallax:.12,editable:true},
    valley:{parallax:.16,editable:true},
    water:{parallax:.18,editable:true},
    heroMountain:{parallax:.22,editable:true},
    structures:{parallax:.24,editable:true},
    trail:{parallax:.25,editable:true},
    mist:{parallax:.28,editable:true},
    foreground:{parallax:.34,editable:true},
    flora:{parallax:.38,editable:true},
    particles:{parallax:.45,editable:true},
    weather:{parallax:.48,editable:true},
    lighting:{parallax:0,editable:true}
  },
  packs:{
    alpine:{
      id:"alpine",name:"Alpine Journey",
      layers:{
        sky:"assets/journey/v79/sky.svg?v=81",
        farMountains:"assets/journey/v79/mountains-back.svg?v=81",
        midMountains:"assets/journey/v79/valley.svg?v=81",
        valley:"assets/journey/v79/valley.svg?v=81",
        heroMountain:"assets/journey/v79/hero-mountain.svg?v=81",
        foreground:"assets/journey/v79/foreground.svg?v=81"
      }
    }
  },
  seasons:{
    spring:{pack:"alpine",overrides:{particles:"petals",weather:"clear",lighting:"springGold",flora:"spring"}},
    summer:{pack:"alpine",overrides:{particles:"none",weather:"clear",lighting:"summerGold",flora:"summer"}},
    fall:{pack:"alpine",overrides:{particles:"leaves",weather:"breeze",lighting:"amber",flora:"fall"}},
    winter:{pack:"alpine",overrides:{particles:"snow",weather:"snow",lighting:"coolGold",flora:"winter"}}
  },
  holidays:{
    halloween:{baseSeason:"fall",decor:["pumpkins","lanterns","ravens"],particles:"embers"},
    christmas:{baseSeason:"winter",decor:["lights","wreaths","gifts"],particles:"snow"},
    newYear:{baseSeason:"winter",decor:["sparkles","banners"],particles:"sparkles"}
  },
  anchors:{
    companionHome:{x:.14,y:.78},
    companionTrail:{x:.38,y:.66},
    companionSummit:{x:.76,y:.22},
    card:{x:.04,y:.08},
    trail:{x:.61,y:.14}
  },
  interactionZones:[
    {id:"trail-start",x:.38,y:.67,w:.16,h:.16},
    {id:"trail-mid",x:.53,y:.48,w:.18,h:.18},
    {id:"summit",x:.69,y:.14,w:.22,h:.22}
  ]
};