window.LQEnvironmentBases={
  version:2,
  slots:[
    {id:"sky",z:1,parallax:.02},
    {id:"celestial",z:2,parallax:.04},
    {id:"farMountains",z:3,parallax:.08},
    {id:"midMountains",z:4,parallax:.12},
    {id:"valley",z:5,parallax:.16},
    {id:"water",z:6,parallax:.18},
    {id:"heroMountain",z:7,parallax:.22},
    {id:"structures",z:8,parallax:.24},
    {id:"mist",z:10,parallax:.28},
    {id:"foreground",z:11,parallax:.34},
    {id:"flora",z:12,parallax:.38},
    {id:"particles",z:13,parallax:.45},
    {id:"weather",z:14,parallax:.48},
    {id:"lighting",z:15,parallax:0}
  ],
  defaultScene:"premium-alpine",
  scenes:{
    "premium-alpine":{
      id:"premium-alpine",
      label:"Premium Alpine",
      layers:{
        sky:window.LQJourneyConfig?.assets?.environment?.premiumAlpine?.runtime||"assets/journey/premium-alpine-v94.webp?v=98"
      },
      effects:{particles:"none",weather:"clear",lighting:"golden",mist:true},
      characterAnchors:{
        home:{
          x:parseFloat(window.LQJourneyConfig?.layout?.companion?.left)||20,
          y:parseFloat(window.LQJourneyConfig?.layout?.companion?.top)||74
        },
        trailStart:{x:39,y:64},
        trailMid:{x:57,y:47},
        summit:{x:76,y:24}
      }
    }
  },
  transition:{
    durationMs:650,
    easing:"cubic-bezier(.22,.8,.24,1)",
    mode:"crossfade"
  }
};
