window.LQSceneConfig={
  version:1,
  activeTheme:"summer",
  themes:{
    spring:{
      id:"spring",label:"Spring",
      layers:{
        sky:"assets/journey/v79/sky.svg?v=79",
        backMountains:"assets/journey/v79/mountains-back.svg?v=79",
        valley:"assets/journey/v79/valley.svg?v=79",
        heroMountain:"assets/journey/v79/hero-mountain.svg?v=79",
        foreground:"assets/journey/v79/foreground.svg?v=79"
      },
      effects:{mist:true,particles:"petals",lighting:"warm",snow:false},
      palette:{gold:"#f2c85f",navy:"#06243d",blue:"#0c8ff0"},
      companionAccessory:null
    },
    summer:{
      id:"summer",label:"Summer",
      layers:{
        sky:"assets/journey/v79/sky.svg?v=79",
        backMountains:"assets/journey/v79/mountains-back.svg?v=79",
        valley:"assets/journey/v79/valley.svg?v=79",
        heroMountain:"assets/journey/v79/hero-mountain.svg?v=79",
        foreground:"assets/journey/v79/foreground.svg?v=79"
      },
      effects:{mist:true,particles:"none",lighting:"golden",snow:false},
      palette:{gold:"#f2c85f",navy:"#06243d",blue:"#0c8ff0"},
      companionAccessory:null
    },
    fall:{
      id:"fall",label:"Fall",
      layers:{
        sky:"assets/journey/v79/sky.svg?v=79",
        backMountains:"assets/journey/v79/mountains-back.svg?v=79",
        valley:"assets/journey/v79/valley.svg?v=79",
        heroMountain:"assets/journey/v79/hero-mountain.svg?v=79",
        foreground:"assets/journey/v79/foreground.svg?v=79"
      },
      effects:{mist:true,particles:"leaves",lighting:"amber",snow:false},
      palette:{gold:"#f0b455",navy:"#06243d",blue:"#0c8ff0"},
      companionAccessory:null
    },
    winter:{
      id:"winter",label:"Winter",
      layers:{
        sky:"assets/journey/v79/sky.svg?v=79",
        backMountains:"assets/journey/v79/mountains-back.svg?v=79",
        valley:"assets/journey/v79/valley.svg?v=79",
        heroMountain:"assets/journey/v79/hero-mountain.svg?v=79",
        foreground:"assets/journey/v79/foreground.svg?v=79"
      },
      effects:{mist:true,particles:"snow",lighting:"coolGold",snow:true},
      palette:{gold:"#f7d982",navy:"#061f38",blue:"#46bfff"},
      companionAccessory:"scarf"
    },
    halloween:{
      id:"halloween",label:"Halloween",
      inherits:"fall",
      effects:{mist:true,particles:"embers",lighting:"moon",snow:false},
      palette:{gold:"#ff9b3d",navy:"#11152a",blue:"#6d63ff"},
      companionAccessory:"pumpkinCharm"
    },
    christmas:{
      id:"christmas",label:"Christmas",
      inherits:"winter",
      effects:{mist:true,particles:"snow",lighting:"festive",snow:true},
      palette:{gold:"#ffd36e",navy:"#06263b",blue:"#38a9ff"},
      companionAccessory:"holidayScarf"
    }
  },
  schedule:[
    {theme:"spring",from:"03-01",to:"05-31"},
    {theme:"summer",from:"06-01",to:"08-31"},
    {theme:"fall",from:"09-01",to:"11-30"},
    {theme:"winter",from:"12-01",to:"02-29"}
  ],
  positions:{
    companion:{left:"4.5%",bottom:"1.5%",width:"31.5%"},
    companionCard:{left:"14px",top:"18px",width:"157px"},
    trail:{right:"-8px",top:"12px",width:"205px",height:"348px"}
  }
};